### ISSUE TITLE
API for knowing the next business time

### ISSUE THREAD

**Issue by take** [bokmann/business_time#109]
as written in [the doc](https://github.com/mokmann/business_time/blob/24ad90e7a115c66dc60fc4247a03e4d8a31a413e/lib/business_time/time_extensions.rb#L26-L27), `BusinessTime::TimeExtensions#workday?` will return `true` even if the time is outside of the normal business time.

which means the returning value of [`BusinessTime::BusinessDays#after`](https://github.com/bokmann/business_time/blob/24ad90e7a115c66dc60fc4247a03e4d8a31a413e/lib/business_time/business_days.rb#L10-L18) might be a time which is outside the normal business time.

I'm not against the spec of those API, but I think there are a large amount of people who would like to know the next business time after X business day.

To enable that, I think we'll need some new APIs for this gem, something like...

1. `BusinessTime::TimeExtensions#business_time?`
    - returns `true` if either of [`BusinessTime::TimeExtensions#before_business_hours?` or `#after_business_hours?`](https://github.com/bokmann/business_time/blob/e2e06ddbf705ba50a721719e8c1c1ce8509e497a/lib/business_time/time_extensions.rb#L46-L52) returns `true`
2. `BusinessTime::TimeExtensions#next_if_not_business_time`
    - returns the next business time if current time isn't business time
    - 1. will be used inside the implementation of this API I guess

wdyt? :O

**Comment by bokmann** [comment]
So the issue is:

Its Wednesday, at 7:30 pm.  While Wednesday is a workday, you're outside of normal business hours.

It makes logical sense that business_day? should still return true, but it would be useful to know if the time is within_business_hours, before_business_hours or after_business_hours.

I like that.

I don't think I like the next_if_not_business_time method... in general, I don't like methods with things like 'if' in the title - business logic is your business.  'if' in a method name is a smell to me.

**Comment by bokmann** [comment]
in fact, we do have before and after business hours methods.
