### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by ACPK** [bokmann/business_time#159]
How does this gem handle daylight savings?

The business hours are set using UTC which does not change with a change of seasons.  However, local time or civil time may change if a time zone jurisdiction observes daylight saving time or summer time.

**Comment by bokmann** [comment]
This gem is timezone-agnostic.  This is an important concept when dealing with timezones...

Most normal people think of daylight savings as 'rolling forward' or 'rolling backward' one hour.  After spending years as a software engineer dealing with this pain, you realize the proper way to think about this is switching timezones.  For instance, even through I'm current sitting in the EDT timezone, the EST timezone still exists, we just aren't using it now.  Come some date later this year, we will change to the other timezone.  The way I think about it is no different than traveling west until I'm in a different timezone.

By thinking about it this way, We can regularly calculate time between two timestamps that are in the same timezone, then deal with the offset due to 'traveling' from one timezone to the other.

I'll work up a code example that makes this concept a little more explicit.
