### ISSUE TITLE
ActiveRecord Support.

### ISSUE THREAD

**Issue by ziweizhou** [bokmann/business_time#98]
Thanks for such great work. 

Is it possible to supply multiple sets of configurations using ActiveRecord? It is possible to have different working days and holiday days for a multi-location based company. 

Thanks a lot

**Comment by asnad** [comment]
I also want to know +1

**Comment by craiglittle** [comment]
Hey, @ziweizhou! I left a similar comment on https://github.com/bokmann/business_time/issues/106, but you should check out a gem we just released called [`biz`](https://github.com/zendesk/biz) that should suit your use case nicely.

Feel free to shoot me an email or open an issue if you have any questions.

**Comment by bokmann** [comment]
I agree that multiple configurations is a useful thing for multi-tenant applications, but that is beyond the purpose of this gem.  As the readme states, I'm all for having a reduced set of functions in order to have a smaller api to the gem.  It looks as if @craiglittle's biz gem should work for you.

**Comment by ziweizhou** [comment]
thank you both @bokmann and @craiglittle  very much
